gb_gestion_bundle_home:
    path: /
    defaults: { _controller: "GPGestionBundle:Default:index" }
    requirements:
        _method: GET
        
gb_gestion_bundle_planning:
    path: /planning
    defaults: { _controller: "GPGestionBundle:Planning:index" }
    
gb_gestion_bundle_planning_interventions:
    path: /planning/interventions
    defaults: { _controller: "GPGestionBundle:Planning:interventions" }
    
gb_gestion_bundle_planning_projets:
    path: /planning/projets
    defaults: { _controller: "GPGestionBundle:Planning:projets" }
    
gb_gestion_bundle_planning_planning:
    path: /planning/planning
    defaults: { _controller: "GPGestionBundle:Planning:planning" }
    
gb_gestion_bundle_parametrage:
    path: /parametrage
    defaults: { _controller: "GPGestionBundle:Parametrage:index" }

gb_gestion_bundle_parametrage_clients:
    path: /parametrage/clients
    defaults: { _controller: "GPGestionBundle:Parametrage:clients" }

gb_gestion_bundle_parametrage_clients_new:
    path: /parametrage/clients/new
    defaults: { _controller: "GPGestionBundle:Parametrage:client" }
    
gb_gestion_bundle_parametrage_clients_edit:
    path: /parametrage/clients/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:client" }
        
gb_gestion_bundle_parametrage_campagnes:
    path: /parametrage/campagnes
    defaults: { _controller: "GPGestionBundle:Parametrage:campagnes" }

gb_gestion_bundle_parametrage_campagnes_new:
    path: /parametrage/campagnes/new
    defaults: { _controller: "GPGestionBundle:Parametrage:campagne" }
    
gb_gestion_bundle_parametrage_campagnes_edit:
    path: /parametrage/campagnes/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:campagne" }
        
    
gb_gestion_bundle_parametrage_poseurs:
    path: /parametrage/poseurs
    defaults: { _controller: "GPGestionBundle:Parametrage:poseurs" }

gb_gestion_bundle_parametrage_poseurs_new:
    path: /parametrage/poseurs/new
    defaults: { _controller: "GPGestionBundle:Parametrage:poseur" }
    
gb_gestion_bundle_parametrage_poseurs_edit:
    path: /parametrage/poseurs/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:poseur" }
        
gb_gestion_bundle_parametrage_chefs:
    path: /parametrage/chefs
    defaults: { _controller: "GPGestionBundle:Parametrage:chefs" }
    
gb_gestion_bundle_parametrage_chefs_new:
    path: /parametrage/chefs/new
    defaults: { _controller: "GPGestionBundle:Parametrage:chef" }
    
gb_gestion_bundle_parametrage_chefs_edit:
    path: /parametrage/chefs/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:chef" }
        
gb_gestion_bundle_parametrage_pointventes:
    path: /parametrage/pointventes
    defaults: { _controller: "GPGestionBundle:Parametrage:pointventes" }

gb_gestion_bundle_parametrage_pointventes_new:
    path: /parametrage/pointventes/new
    defaults: { _controller: "GPGestionBundle:Parametrage:pointvente" }
    
gb_gestion_bundle_parametrage_pointventes_edit:
    path: /parametrage/pointventes/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:pointvente" }
     
gb_gestion_bundle_parametrage_societes:
    path: /parametrage/societes
    defaults: { _controller: "GPGestionBundle:Parametrage:societes" }

gb_gestion_bundle_parametrage_societes_new:
    path: /parametrage/societes/new
    defaults: { _controller: "GPGestionBundle:Parametrage:societe" }
    
gb_gestion_bundle_parametrage_societes_edit:
    path: /parametrage/societes/edit/{id}
    defaults: { _controller: "GPGestionBundle:Parametrage:societe" }
                        
gb_gestion_bundle_options:
    path: /options
    defaults: { _controller: "GPGestionBundle:Options:index" }    