<?php

namespace GP\GestionBundle\Repository;

/**
 * ChefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChefRepository extends \Doctrine\ORM\EntityRepository
{
}
