<?php

namespace GP\GestionBundle\Repository;

/**
 * InterventionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
