<?php

namespace GP\GestionBundle\Repository;

/**
 * InterventionStatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterventionStatutRepository extends \Doctrine\ORM\EntityRepository
{
}
