<?php

namespace GP\GestionBundle\Repository;

/**
 * PointventeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointventeRepository extends \Doctrine\ORM\EntityRepository
{
}
