<?php

namespace GP\GestionBundle\Repository;

/**
 * PoseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PoseurRepository extends \Doctrine\ORM\EntityRepository
{
}
