gp_front:
    resource: "@GPFrontBundle/Resources/config/routing.yml"
    prefix:   /

gp_main:
    resource: "@GPMainBundle/Resources/config/routing.yml"
    prefix:   /

gp_gestion:
    resource: "@GPGestionBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
