# SECURITY
gp_gestion_security:
    resource: "@GPGestionBundle/Resources/config/routing/security.yml"

# BACKOFFICE
gp_gestion_bo:
    resource: "@GPGestionBundle/Resources/config/routing/gestion.yml"