gp_front_homepage:
    path:     /
    defaults: { _controller: GPFrontBundle:Default:index }

gp_front_webservice_login:
    path:     /webservice/login
    defaults: { _controller: GPFrontBundle:Webservice:login }

gp_front_webservice_list:
    path:     /webservice/list
    defaults: { _controller: GPFrontBundle:Webservice:list }
gp_front_webservice_intervention:
    path:     /webservice/intervention
    defaults: { _controller: GPFrontBundle:Webservice:intervention }        
gp_front_webservice_intervention_save:
    path:     /webservice/save
    defaults: { _controller: GPFrontBundle:Webservice:save }    
# SECURITY
#gp_front_security:
 #   resource: "@GPFrontBundle/Resources/config/routing/security.yml"
    
    
    